export const data = [
  {
    id: 1,
    first_name: 'Phyllis',
    last_name: 'Farreil',
    address: '0823 Ronald Regan Lane',
    city: 'Xiaojiang',
    geo: 1,
    date: '9/18/2019',
    status: false,
    phone: '642-316-7619',
    apartment_nr: '363',
    request: 'captopril',
    has_money: true,
    curator: true,
    comments: [{}]
  },
  {
    id: 2,
    first_name: 'Kermit',
    last_name: 'Foord',
    address: '709 Katie Way',
    city: 'Dante Delgado',
    geo: 2,
    date: '7/12/2019',
    status: true,
    phone: '822-965-4449',
    apartment_nr: '2',
    request: 'Glyburide',
    has_money: true,
    curator: true,
    comments: [{}, {}, {}, {}, {}]
  },
  {
    id: 3,
    first_name: 'Tris',
    last_name: 'Haggett',
    address: '9 Vera Place',
    city: 'Saumur',
    geo: 2,
    date: '1/6/2020',
    status: false,
    phone: '917-175-7309',
    apartment_nr: '62804',
    request: 'METHYL SALICYLATE MENTHOL CAPSAICIN LIDOCAINE',
    has_money: true,
    curator: false,
    comments: [{}, {}, {}, {}, {}]
  },
  {
    id: 4,
    first_name: 'Baxy',
    last_name: 'Taffrey',
    address: '76794 Londonderry Crossing',
    city: 'Huasta',
    geo: 1,
    date: '2/22/2020',
    status: false,
    phone: '170-224-0355',
    apartment_nr: '2',
    request: 'DIPHENHYDRAMINE HYDROCHLORIDE',
    has_money: false,
    curator: true,
    comments: [{}]
  },
  {
    id: 5,
    first_name: 'Walden',
    last_name: 'Torres',
    address: '9 Sutherland Point',
    city: 'Madrid',
    geo: 2,
    date: '10/26/2019',
    status: true,
    phone: '775-367-3711',
    apartment_nr: '01956',
    request:
      'Allium sativum, Berberis vulgaris, Glycyrrhiza glabra, Lappa major, Phytolacca Decandra, Rahmnus frangula, Stillingia sylvatica,',
    has_money: true,
    curator: true,
    comments: [{}, {}]
  },
  {
    id: 6,
    first_name: 'Bevin',
    last_name: 'Hartigan',
    address: '34 Atwood Avenue',
    city: 'Dafang',
    geo: 1,
    date: '8/4/2019',
    status: false,
    phone: '746-793-4889',
    apartment_nr: '81733',
    request: 'Phenytoin Sodium',
    has_money: false,
    curator: true,
    comments: [{}, {}, {}]
  },
  {
    id: 7,
    first_name: 'Ruttger',
    last_name: 'Dewett',
    address: '09172 Sunbrook Place',
    city: 'Maple Plain',
    geo: 1,
    date: '1/17/2020',
    status: false,
    phone: '952-166-9244',
    apartment_nr: '49607',
    request: 'Doxorubicin Hydrochloride',
    has_money: false,
    curator: false,
    comments: [{}, {}, {}]
  },
  {
    id: 8,
    first_name: 'Shannon',
    last_name: 'Maseres',
    address: '8899 Katie Hill',
    city: 'Saint-Denis',
    geo: 3,
    date: '11/20/2019',
    status: false,
    phone: '500-194-7087',
    apartment_nr: '3342',
    request: 'Nicotine Polacrilex',
    has_money: false,
    curator: false,
    comments: [{}, {}, {}]
  },
  {
    id: 9,
    first_name: 'Gerome',
    last_name: 'Couthard',
    address: '38618 Lakewood Gardens Point',
    city: 'Yanhu',
    geo: 1,
    date: '7/6/2019',
    status: false,
    phone: '644-353-9695',
    apartment_nr: '31',
    request: 'minocycline hydrochloride',
    has_money: true,
    curator: false,
    comments: [{}, {}, {}]
  },
  {
    id: 10,
    first_name: 'Dorri',
    last_name: 'Clerke',
    address: '84684 Londonderry Street',
    city: 'Lyon',
    geo: 3,
    date: '4/18/2019',
    status: true,
    phone: '678-917-7356',
    apartment_nr: '56',
    request: 'OATMEAL',
    has_money: true,
    curator: true,
    comments: [{}, {}, {}, {}]
  },
  {
    id: 11,
    first_name: 'Jeth',
    last_name: 'Colombier',
    address: '30949 Darwin Terrace',
    city: 'Keyi',
    geo: 1,
    date: '8/31/2019',
    status: false,
    phone: '723-812-8243',
    apartment_nr: '70982',
    request: 'Paroxetine Hydrochloride',
    has_money: true,
    curator: true,
    comments: [{}, {}, {}, {}, {}]
  },
  {
    id: 12,
    first_name: 'Ilise',
    last_name: 'Neame',
    address: '68986 Holmberg Avenue',
    city: 'Xitou',
    geo: 1,
    date: '12/8/2019',
    status: true,
    phone: '175-508-8543',
    apartment_nr: '590',
    request: 'Digoxin',
    has_money: true,
    curator: true,
    comments: [{}, {}, {}, {}, {}]
  },
  {
    id: 13,
    first_name: 'Demetris',
    last_name: 'Sigfrid',
    address: '7211 Toban Road',
    city: 'Tall aḑ Ḑamān',
    geo: 3,
    date: '6/18/2019',
    status: false,
    phone: '899-608-2577',
    apartment_nr: '94',
    request: 'Flecainide Acetate',
    has_money: false,
    curator: false,
    comments: [{}, {}]
  },
  {
    id: 14,
    first_name: 'Wayne',
    last_name: 'Ivasechko',
    address: '0433 Roxbury Point',
    city: 'Greensboro',
    geo: 1,
    date: '7/20/2019',
    status: false,
    phone: '336-862-8673',
    apartment_nr: '8',
    request: 'Acetaminophen',
    has_money: true,
    curator: true,
    comments: [{}, {}, {}, {}]
  },
  {
    id: 15,
    first_name: 'Konstantin',
    last_name: 'Roder',
    address: '3 Derek Way',
    city: 'Ciomas',
    geo: 3,
    date: '12/26/2019',
    status: false,
    phone: '815-557-9800',
    apartment_nr: '661',
    request: 'Dibasic sodium phosphate, Monobasic sodium phosphate',
    has_money: true,
    curator: false,
    comments: [{}, {}, {}]
  },
  {
    id: 16,
    first_name: 'Terrie',
    last_name: 'Benford',
    address: '5010 Scott Place',
    city: 'Curahkalak Tengah',
    geo: 1,
    date: '12/19/2019',
    status: false,
    phone: '876-188-9355',
    apartment_nr: '18760',
    request: 'ceftibuten dihydrate',
    has_money: false,
    curator: false,
    comments: [{}]
  },
  {
    id: 17,
    first_name: 'Caryl',
    last_name: 'Dublin',
    address: '82 Springs Way',
    city: 'Krasnaya Gorka',
    geo: 2,
    date: '3/21/2020',
    status: true,
    phone: '182-540-0703',
    apartment_nr: '92',
    request: 'fenoprofen',
    has_money: true,
    curator: true,
    comments: [{}]
  },
  {
    id: 18,
    first_name: 'Regina',
    last_name: 'Hurford',
    address: '98460 International Plaza',
    city: 'Sarangmeduro',
    geo: 4,
    date: '2/1/2020',
    status: true,
    phone: '526-441-7183',
    apartment_nr: '45',
    request: 'Silver Maple',
    has_money: false,
    curator: true,
    comments: [{}, {}]
  },
  {
    id: 19,
    first_name: 'Jenni',
    last_name: 'Nassey',
    address: '3 Lien Way',
    city: 'Erada',
    geo: 2,
    date: '6/15/2019',
    status: true,
    phone: '105-960-2155',
    apartment_nr: '9',
    request: 'Octinoxate and Oxybenzone',
    has_money: true,
    curator: false,
    comments: [{}, {}, {}, {}]
  },
  {
    id: 20,
    first_name: 'Sheeree',
    last_name: 'Noden',
    address: '7 Kedzie Plaza',
    city: 'El Cafetal',
    geo: 1,
    date: '1/14/2020',
    status: false,
    phone: '940-756-0027',
    apartment_nr: '83',
    request: 'OCTINOXATE, TITANIUM DIOXIDE',
    has_money: false,
    curator: false,
    comments: [{}, {}, {}, {}]
  },
  {
    id: 21,
    first_name: 'Abbe',
    last_name: 'Mertel',
    address: '9296 Cody Street',
    city: 'Xiaochi',
    geo: 1,
    date: '6/2/2019',
    status: false,
    phone: '955-316-3675',
    apartment_nr: '579',
    request: 'Camphor (Synthetic) and Menthol',
    has_money: true,
    curator: true,
    comments: [{}]
  },
  {
    id: 22,
    first_name: 'Savina',
    last_name: 'McCarty',
    address: '61948 Russell Street',
    city: 'Karak',
    geo: 1,
    date: '1/1/2020',
    status: true,
    phone: '387-291-2590',
    apartment_nr: '56694',
    request: 'Plantain English',
    has_money: true,
    curator: false,
    comments: [{}, {}, {}, {}, {}]
  },
  {
    id: 23,
    first_name: 'Matthiew',
    last_name: 'Peye',
    address: '1 Harbort Parkway',
    city: 'Yongdeng Chengguanzhen',
    geo: 4,
    date: '2/14/2020',
    status: false,
    phone: '265-515-3898',
    apartment_nr: '0780',
    request: 'RIFAMPIN',
    has_money: true,
    curator: false,
    comments: [{}]
  },
  {
    id: 24,
    first_name: 'Yanaton',
    last_name: 'Duckinfield',
    address: '3 Meadow Vale Avenue',
    city: 'Pedaringan',
    geo: 12,
    date: '5/3/2019',
    status: false,
    phone: '810-883-8197',
    apartment_nr: '7283',
    request: 'Loperamide Hydrochloride',
    has_money: true,
    curator: true,
    comments: [{}]
  },
  {
    id: 25,
    first_name: 'Kalindi',
    last_name: 'Keynes',
    address: '60 Raven Avenue',
    city: 'Kawaguchi',
    geo: 1,
    date: '7/4/2019',
    status: false,
    phone: '875-840-3242',
    apartment_nr: '58818',
    request: 'Hydralazine Hydrochloride',
    has_money: false,
    curator: true,
    comments: [{}]
  },
  {
    id: 26,
    first_name: 'Jens',
    last_name: 'Heball',
    address: '04904 Heffernan Crossing',
    city: 'Mölndal',
    geo: 1,
    date: '7/26/2019',
    status: true,
    phone: '945-388-4232',
    apartment_nr: '40522',
    request: 'DIOSCOREA VILLOSA ROOT GINGER',
    has_money: false,
    curator: false,
    comments: [{}, {}, {}, {}]
  },
  {
    id: 27,
    first_name: 'Elton',
    last_name: 'Pistol',
    address: '6 Main Crossing',
    city: 'Kharagauli',
    geo: 1,
    date: '4/17/2019',
    status: false,
    phone: '319-531-9230',
    apartment_nr: '900',
    request: 'Ultramicrosize Griseofulvin Tablets',
    has_money: true,
    curator: false,
    comments: [{}, {}, {}, {}, {}]
  },
  {
    id: 28,
    first_name: 'Kessiah',
    last_name: 'Stidever',
    address: '750 Schurz Place',
    city: 'Tuchów',
    geo: 2,
    date: '5/13/2019',
    status: true,
    phone: '816-573-5082',
    apartment_nr: '62587',
    request: 'estradiol and norethindrone acetate',
    has_money: false,
    curator: false,
    comments: [{}, {}]
  },
  {
    id: 29,
    first_name: 'Jonell',
    last_name: 'Bracci',
    address: '705 Caliangt Pass',
    city: 'Katipunan',
    geo: 1,
    date: '1/3/2020',
    status: false,
    phone: '219-997-9393',
    apartment_nr: '44',
    request: 'Ranitidine',
    has_money: false,
    curator: true,
    comments: [{}, {}, {}, {}, {}]
  },
  {
    id: 30,
    first_name: 'Sheree',
    last_name: "O'Doireidh",
    address: '8 Moulton Trail',
    city: 'Santa Fe',
    geo: 3,
    date: '8/12/2019',
    status: true,
    phone: '680-565-6445',
    apartment_nr: '81927',
    request: 'Viscum 3',
    has_money: false,
    curator: false,
    comments: [{}, {}]
  },
  {
    id: 31,
    first_name: 'Gisele',
    last_name: 'Colcomb',
    address: '68435 Mallory Court',
    city: 'Rosais',
    geo: 2,
    date: '9/11/2019',
    status: false,
    phone: '193-384-7776',
    apartment_nr: '5',
    request:
      'Dextromethorphan Hydrobromide, Guaifenesin, and Pseudoephedrine Hydrochloride',
    has_money: true,
    curator: false,
    comments: [{}, {}]
  },
  {
    id: 32,
    first_name: 'Horatio',
    last_name: 'McKendry',
    address: '71530 Bay Junction',
    city: 'Osogbo',
    geo: 1,
    date: '5/27/2019',
    status: true,
    phone: '152-316-7994',
    apartment_nr: '287',
    request: 'Prednisone',
    has_money: true,
    curator: true,
    comments: [{}, {}, {}, {}]
  },
  {
    id: 33,
    first_name: 'Aguie',
    last_name: 'Glenny',
    address: '537 Cardinal Way',
    city: 'Bremen',
    geo: 2,
    date: '12/25/2019',
    status: true,
    phone: '401-678-4359',
    apartment_nr: '7',
    request: 'Acyclovir',
    has_money: true,
    curator: true,
    comments: [{}, {}, {}]
  },
  {
    id: 34,
    first_name: 'Jeremias',
    last_name: 'Stiller',
    address: '69 Algoma Lane',
    city: 'Leifeng',
    geo: 7,
    date: '10/5/2019',
    status: true,
    phone: '637-474-3397',
    apartment_nr: '2',
    request: 'Butalbital, Acetaminophen, and Caffeine',
    has_money: false,
    curator: false,
    comments: [{}, {}, {}]
  },
  {
    id: 35,
    first_name: 'Aguie',
    last_name: 'Dureden',
    address: '781 Dunning Point',
    city: 'Novocheboksarsk',
    geo: 1,
    date: '2/20/2020',
    status: true,
    phone: '452-587-4731',
    apartment_nr: '76',
    request: 'Quinapril',
    has_money: false,
    curator: true,
    comments: [{}, {}, {}, {}]
  },
  {
    id: 36,
    first_name: 'Ardene',
    last_name: 'Woofendell',
    address: '794 Bashford Lane',
    city: 'Huoqiu Chengguanzhen',
    geo: 1,
    date: '10/13/2019',
    status: true,
    phone: '932-637-4853',
    apartment_nr: '680',
    request: 'Octinoxate',
    has_money: false,
    curator: false,
    comments: [{}, {}, {}, {}, {}]
  },
  {
    id: 37,
    first_name: 'Ernaline',
    last_name: 'Gray',
    address: '44586 Rowland Pass',
    city: 'Stockholm',
    geo: 5,
    date: '11/27/2019',
    status: false,
    phone: '821-799-0681',
    apartment_nr: '2813',
    request: 'POLYETHYLENE GLYCOL 3350',
    has_money: false,
    curator: false,
    comments: [{}, {}, {}, {}, {}]
  },
  {
    id: 38,
    first_name: 'Hermann',
    last_name: 'Seagar',
    address: '9059 Charing Cross Alley',
    city: 'Waenenda',
    geo: 2,
    date: '8/6/2019',
    status: true,
    phone: '382-270-5474',
    apartment_nr: '2',
    request: 'Sodium Monofluorophosphate',
    has_money: true,
    curator: false,
    comments: [{}, {}, {}, {}, {}]
  },
  {
    id: 39,
    first_name: 'Merrill',
    last_name: 'Wedgwood',
    address: '178 Columbus Center',
    city: 'Rio Formoso',
    geo: 1,
    date: '10/26/2019',
    status: true,
    phone: '660-876-0551',
    apartment_nr: '3623',
    request: 'INATAL Ultra',
    has_money: false,
    curator: false,
    comments: [{}, {}, {}]
  },
  {
    id: 40,
    first_name: 'Sal',
    last_name: 'MacQuaker',
    address: '26091 Granby Trail',
    city: 'Bali',
    geo: 3,
    date: '11/30/2019',
    status: false,
    phone: '485-950-2728',
    apartment_nr: '51',
    request: 'Gabapentin',
    has_money: false,
    curator: false,
    comments: [{}, {}]
  },
  {
    id: 41,
    first_name: 'Elfie',
    last_name: 'Merrigan',
    address: '86 Graedel Street',
    city: 'Taoyuan',
    geo: 2,
    date: '3/14/2020',
    status: true,
    phone: '219-378-7718',
    apartment_nr: '55321',
    request: 'Tramadol Hydrochloride Tablets',
    has_money: false,
    curator: false,
    comments: [{}, {}]
  },
  {
    id: 42,
    first_name: 'Abie',
    last_name: 'Thornborrow',
    address: '5357 Bashford Drive',
    city: 'Lazeshchyna',
    geo: 1,
    date: '9/24/2019',
    status: false,
    phone: '941-823-4296',
    apartment_nr: '0',
    request: 'Benzoyl Peroxide',
    has_money: false,
    curator: false,
    comments: [{}, {}, {}, {}]
  },
  {
    id: 43,
    first_name: 'Derick',
    last_name: 'Maytom',
    address: '463 Evergreen Terrace',
    city: 'Caldas Novas',
    geo: 1,
    date: '9/19/2019',
    status: false,
    phone: '465-623-6012',
    apartment_nr: '1',
    request: 'Oxygen',
    has_money: true,
    curator: false,
    comments: [{}, {}, {}]
  },
  {
    id: 44,
    first_name: 'Wendel',
    last_name: 'Gerkens',
    address: '5281 Village Green Lane',
    city: 'Mkiriwadjumoi',
    geo: 3,
    date: '5/27/2019',
    status: true,
    phone: '542-841-5688',
    apartment_nr: '3',
    request: 'Benzalkonium chloride',
    has_money: true,
    curator: false,
    comments: [{}, {}, {}, {}, {}]
  },
  {
    id: 45,
    first_name: 'Carlita',
    last_name: 'Gleed',
    address: '66176 Marcy Way',
    city: 'Strasbourg',
    geo: 2,
    date: '12/22/2019',
    status: true,
    phone: '135-642-9566',
    apartment_nr: '314',
    request: 'Hydrocodone Bitartate and Acetaminophen',
    has_money: false,
    curator: true,
    comments: [{}]
  },
  {
    id: 46,
    first_name: 'Dewey',
    last_name: 'Coryndon',
    address: '55 Macpherson Pass',
    city: 'Enonkoski',
    geo: 1,
    date: '4/26/2019',
    status: false,
    phone: '719-693-5256',
    apartment_nr: '3',
    request: 'OCTINOXATE and OXYBENZONE',
    has_money: true,
    curator: true,
    comments: [{}, {}, {}, {}, {}]
  },
  {
    id: 47,
    first_name: 'Jackie',
    last_name: 'Handyside',
    address: '5347 Green Plaza',
    city: 'Walakeri',
    geo: 2,
    date: '11/30/2019',
    status: true,
    phone: '561-270-2500',
    apartment_nr: '958',
    request: 'Venlafaxine',
    has_money: true,
    curator: false,
    comments: [{}]
  },
  {
    id: 48,
    first_name: 'Arabela',
    last_name: 'Hagstone',
    address: '8 Alpine Junction',
    city: 'Faaone',
    geo: 3,
    date: '12/8/2019',
    status: false,
    phone: '409-946-6247',
    apartment_nr: '9',
    request: 'ZINC GLUCONATE and ZINC ACETATE',
    has_money: false,
    curator: false,
    comments: [{}, {}]
  },
  {
    id: 49,
    first_name: 'Madelon',
    last_name: 'Metham',
    address: '22922 Sunnyside Lane',
    city: 'Kaélé',
    geo: 1,
    date: '5/31/2019',
    status: false,
    phone: '962-752-7534',
    apartment_nr: '95',
    request: 'TITANIUM DIOXIDE, ZINC OXIDE',
    has_money: false,
    curator: true,
    comments: [{}, {}]
  },
  {
    id: 50,
    first_name: 'Veronika',
    last_name: "O'Hagan",
    address: '88023 Meadow Valley Street',
    city: 'Vũ Quang',
    geo: 1,
    date: '3/20/2020',
    status: false,
    phone: '230-352-2758',
    apartment_nr: '802',
    request: 'ondansetron hydrochloride',
    has_money: false,
    curator: false,
    comments: [{}]
  }
];
